import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ModalProvider from "@/providers/ModalProvider";
import { GuessProvider } from "@/providers/DataProvider";
import HomeProvider from "@/providers/HomeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HomeProvider>
          <GuessProvider>
            {children}
            <ModalProvider />
          </GuessProvider>
        </HomeProvider>
      </body>
    </html>
  );
}
